# Generated by Django 5.0.3 on 2024-04-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helados', '0002_pedido_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_bolas',
            field=models.IntegerField(default=0),
        ),
    ]
