# Generated by Django 5.0.3 on 2024-04-15 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helados', '0004_remove_detallepedido_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabor',
            name='num_bolas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
