# Generated by Django 5.0.3 on 2024-04-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helados', '0005_sabor_num_bolas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sabor',
            name='num_bolas',
        ),
    ]
