# Generated by Django 5.0.3 on 2024-04-22 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helados', '0006_remove_sabor_num_bolas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('numero_bolas', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('helado_recipiente_cristal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helados.heladorecipientecristal')),
                ('recipiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helados.recipiente')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoHelado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_helado', to='helados.pedido')),
                ('sabor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helados.sabor')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='sabores',
            field=models.ManyToManyField(blank=True, through='helados.PedidoHelado', to='helados.sabor'),
        ),
    ]
