# Generated by Django 5.0.3 on 2024-04-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helados', '0007_pedido_pedidohelado_pedido_sabores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidohelado',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidohelado',
            name='sabor',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoHelado',
        ),
    ]
