# Generated by Django 5.0.3 on 2024-05-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helados', '0008_remove_pedidohelado_pedido_remove_pedidohelado_sabor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipiente',
        ),
    ]
